// posts page
export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_AUTHORS = 'FETCH_AUTHORS';
export const FETCH_POSTS_FAILED = 'FETCH_POSTS_FAILED'
export const FETCH_CATEGORIES_FAILED = 'FETCH_CATEGORIES_FAILED'
export const FETCH_AUTHORS_FAILED = 'FETCH_AUTHORS_FAILED'

// individual posts page
export const SELECT_POST = 'SELECT_POST';
export const ACTIVE_POST = 'ACTIVE_POST';
export const ACTIVE_POST_FETCH_FAILED = 'ACTIVE_POST_FETCH_FAILED';
export const ACTIVE_POST_CATEGORY_ID = 'ACTIVE_POST_CATEGORY_ID';

// category
export const ACTIVE_CATEGORY_ID = 'ACTIVE_CATEGORY_ID';
export const SET_CATEGORY_ID_TO_NULL = 'SET_CATEGORY_ID_TO_NULL';